site_name: Isabella Gross Alström
site_author: Isabella Gross Alström
theme:
  name: 'material'

  palette:
    primary: 'green'
    accent: 'indigo'
nav:
  - Home: index.md
  - Home Assistant: hass.md 
  - Ecosystem: 
      - 'My Smart Home': 'ecosystem.md'
      - 'Batteries': 'batteries.md'
  - Lovelace: lovelace.md
  - Addons: hassio-addons.md
  - Components: components.md
  - Presence Detection: presence-detection.md
  - My Hass development: dev.md

  - Linux Commands: linux-commands.md
  - Featured: featured.md

repo_url: https://github.com/isabellaalstrom/HomeAssistantConfiguration
repo_name: My Home Assistant Config
site_url: 'https://isabellaalstrom.github.io/'
edit_uri: null

extra:
  disqus: 'isabellaalstrom'
  social:
    - type: 'github'
      link: 'https://github.com/isabellaalstrom'
    - type: 'twitter'
      link: 'https://twitter.com/teachingbirds'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/isabellaalstrom/'

google_analytics: ['UA-133907099-1', 'isabellaalstrom.se']
markdown_extensions:
  - admonition
  # - pymdownx.attr_list
  - pymdownx.tilde
  # - zoomify