site_name: Isabella Gross Alström
site_author: Isabella Gross Alström
theme:
  name: 'material'

  palette:
    primary: 'green'
    accent: 'indigo'
nav:
  - Home: index.md
  - Home Assistant: 000-hass.md 
  - Ecosystem: 001-ecosystem.md
  - Lovelace: 002-lovelace.md
  - Addons: 003-hassio-addons.md
  - Components: 004-components.md
  - Presence Detection: 005-presence-detection.md

  - Linux Commands: 999-linux-commands.md

repo_url: https://github.com/isabellaalstrom/HomeAssistantConfiguration
repo_name: My Home Assistant Config
google_analytics: ['UA-133907099-1', 'isabellaalstrom.se']