site_name: Isabella Gross Alström
site_author: Isabella Gross Alström
theme:
  name: 'material'

  palette:
    primary: 'green'
    accent: 'indigo'
nav:
  - Home: index.md
  - Home Assistant: hass.md 
  - Ecosystem: ecosystem.md
  - Lovelace: lovelace.md
  - Addons: hassio-addons.md
  - Components: components.md
  - Presence Detection: presence-detection.md

  - Linux Commands: linux-commands.md
  - Featured: featured.md

repo_url: https://github.com/isabellaalstrom/HomeAssistantConfiguration
repo_name: My Home Assistant Config
google_analytics: ['UA-133907099-1', 'isabellaalstrom.se']